const LARGEST_SIZE = 1280;
const SMALL_SIZE = 480;

const RENDER_MOVIES_LARGE = 12;
const RENDER_MOVIES_MEDIUM = 8;
const RENDER_MOVIES_SMALL = 5;

const ZERO_NUMBER = 0;

const MOVIES_TO_ADD_LARGE = 3;
const MOVIES_TO_ADD_MEDIUM = 2;

export {
  LARGEST_SIZE,
  SMALL_SIZE,
  RENDER_MOVIES_LARGE,
  RENDER_MOVIES_MEDIUM,
  RENDER_MOVIES_SMALL,
  ZERO_NUMBER,
  MOVIES_TO_ADD_LARGE,
  MOVIES_TO_ADD_MEDIUM
}